// <auto-generated />
using System;
using DevPilotAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevPilotAgent.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DevPilotAgent.Domain.Entities.AnalysisRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedKeywordsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FixSuggestionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedFilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCauseAnalysis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestScenariosJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AnalysisRecords_CreatedAt");

                    b.ToTable("AnalysisRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
